# Generated by Django 5.0.1 on 2024-01-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(upload_to='MenuItemImages/<django.db.models.fields.IntegerField>.png'),
        ),
    ]
