# Generated by Django 5.0.1 on 2024-02-01 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_menuitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderID', models.IntegerField(primary_key=True, serialize=False)),
                ('table', models.IntegerField()),
                ('menuItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.menuitem')),
            ],
        ),
    ]
