# Generated by Django 5.0.1 on 2024-02-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_orders_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('CKG', 'Cooking'), ('RTC', 'Ready to collect'), ('COM', 'Completed')], default='CKG', max_length=3),
            preserve_default=False,
        ),
    ]
