# Generated by Django 5.0.1 on 2024-02-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_ingredientinclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiterCall',
            fields=[
                ('waiterCallID', models.IntegerField(primary_key=True, serialize=False)),
                ('table', models.IntegerField()),
                ('message', models.CharField(max_length=350)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
