# Generated by Django 5.0.1 on 2024-02-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_orders_status'),
        ('app', '0010_waitercall'),
    ]

    operations = [
    ]
