# Generated by Django 4.2.9 on 2024-02-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_waitercall'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menuType',
            field=models.CharField(default='mains', max_length=200),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='spice',
            field=models.CharField(default='spiceless', max_length=200),
        ),
    ]
