# Generated by Django 5.0.1 on 2024-02-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_merge_0008_orders_status_0010_waitercall'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='available',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
