# Generated by Django 4.2.9 on 2024-02-16 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_menuitem_menutype_menuitem_spice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='menuType',
            new_name='category',
        ),
    ]
