# Generated by Django 4.2.9 on 2024-02-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_menutype_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='allergy',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
