# Generated by Django 5.0.1 on 2024-02-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_menuitem_available'),
        ('app', '0013_menuitem_allergy'),
    ]

    operations = [
    ]
