# Generated by Django 5.0.1 on 2024-03-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_waitercall_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.CharField(default='delicious meal', max_length=1000),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('CKG', 'Cooking'), ('COM', 'Completed'), ('REC', 'Received'), ('RTC', 'Ready to collect')], max_length=3),
        ),
    ]
