# Generated by Django 5.0.1 on 2024-03-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_waitercall_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('RTC', 'Ready to collect'), ('COM', 'Completed'), ('CKG', 'Cooking'), ('REC', 'Received')], max_length=3),
        ),
    ]
