# Generated by Django 5.0.1 on 2024-03-14 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_orders_status'),
        ('app', '0016_menuitem_description_alter_orders_status'),
    ]

    operations = [
    ]
