# Generated by Django 5.0.1 on 2024-03-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_merge_20240314_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.CharField(default='Delicious meal', max_length=1000),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('REC', 'Received'), ('RTC', 'Ready to collect'), ('COM', 'Completed'), ('CKG', 'Cooking')], max_length=3),
        ),
    ]
