# Generated by Django 5.0.1 on 2024-03-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_menuitem_description_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('mains', 'Main'), ('starters', 'Starter'), ('desserts', 'Dessert'), ('drinks', 'Drink')], default='mains', max_length=200),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='spice',
            field=models.CharField(choices=[('atomic', 'Atomic'), ('hot', 'Hot'), ('spiceless', 'Spiceless'), ('mild', 'Mild')], default='spiceless', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('RTC', 'Ready to collect'), ('CKG', 'Cooking'), ('COM', 'Completed'), ('REC', 'Received')], max_length=3),
        ),
    ]
