# Generated by Django 5.0.1 on 2024-03-14 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_menuitem_category_alter_menuitem_spice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='calories',
            field=models.IntegerField(default=150, validators=[django.core.validators.MaxValueValidator(3500)]),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('starters', 'Starter'), ('drinks', 'Drink'), ('desserts', 'Dessert'), ('mains', 'Main')], default='mains', max_length=200),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='spice',
            field=models.CharField(choices=[('hot', 'Hot'), ('atomic', 'Atomic'), ('spiceless', 'Spiceless'), ('mild', 'Mild')], default='spiceless', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('REC', 'Received'), ('CKG', 'Cooking'), ('COM', 'Completed'), ('RTC', 'Ready to collect')], max_length=3),
        ),
    ]
