# Generated by Django 5.0.1 on 2024-03-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_menuitem_category_alter_menuitem_spice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('mains', 'Main'), ('starters', 'Starter'), ('desserts', 'Dessert'), ('drinks', 'Drink')], default='mains', max_length=200),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='spice',
            field=models.CharField(choices=[('spiceless', 'Spiceless'), ('atomic', 'Atomic'), ('mild', 'Mild'), ('hot', 'Hot')], default='spiceless', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('UPD', 'Not paid for'), ('RTC', 'Ready to collect'), ('REC', 'Received'), ('CKG', 'Cooking'), ('COM', 'Completed')], max_length=3),
        ),
    ]
