# Generated by Django 5.0.1 on 2024-03-18 20:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_menuitem_calories_alter_menuitem_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('expiration_date', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('payment_method', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='orders',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('starters', 'Starter'), ('mains', 'Main'), ('desserts', 'Dessert'), ('drinks', 'Drink')], default='mains', max_length=200),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.CharField(default='Delicious meal', max_length=180),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='spice',
            field=models.CharField(choices=[('hot', 'Hot'), ('spiceless', 'Spiceless'), ('atomic', 'Atomic'), ('mild', 'Mild')], default='spiceless', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('REC', 'Received'), ('COM', 'Completed'), ('RTC', 'Ready to collect'), ('CKG', 'Cooking')], max_length=3),
        ),
    ]
