# Generated by Django 5.0.1 on 2024-03-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_paymentauthorization_alter_orders_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='caloriesPer100g',
        ),
        migrations.RemoveField(
            model_name='ingredientinclusion',
            name='quantityGrams',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredientID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('starters', 'Starter'), ('drinks', 'Drink'), ('desserts', 'Dessert'), ('mains', 'Main')], default='mains', max_length=200),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='spice',
            field=models.CharField(choices=[('mild', 'Mild'), ('spiceless', 'Spiceless'), ('atomic', 'Atomic'), ('hot', 'Hot')], default='spiceless', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('CKG', 'Cooking'), ('REC', 'Received'), ('RTC', 'Ready to collect'), ('COM', 'Completed')], max_length=3),
        ),
    ]
