# Generated by Django 5.0.1 on 2024-03-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_menuitem_category_alter_menuitem_spice_and_more'),
        ('app', '0023_remove_ingredient_caloriesper100g_and_more'),
    ]

    operations = [
    ]
