# Generated by Django 5.0.1 on 2024-03-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_menuitem_allergy_alter_menuitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='allergy',
            field=models.CharField(choices=[('vegetarian', 'Vegetarian'), ('dairy', 'Dairy'), ('gluten', 'Gluten'), ('nuts', 'Nuts'), ('none', 'None')], default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('drinks', 'Drink'), ('mains', 'Main'), ('desserts', 'Dessert'), ('starters', 'Starter')], default='mains', max_length=30),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='spice',
            field=models.CharField(choices=[('mild', 'Mild'), ('spiceless', 'Spiceless'), ('hot', 'Hot'), ('atomic', 'Atomic')], default='spiceless', max_length=15),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('UPD', 'Not paid for'), ('REC', 'Received'), ('COM', 'Completed'), ('RTC', 'Ready to collect'), ('CKG', 'Cooking')], max_length=3),
        ),
    ]
