# Generated by Django 5.0.1 on 2024-03-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_menuitem_allergy_alter_menuitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentauthorization',
            name='table_number',
            field=models.IntegerField(default=41),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentauthorization',
            name='total_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='allergy',
            field=models.CharField(choices=[('vegetarian', 'Vegetarian'), ('none', 'None'), ('nuts', 'Nuts'), ('gluten', 'Gluten'), ('dairy', 'Dairy')], default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('starters', 'Starter'), ('drinks', 'Drink'), ('mains', 'Main'), ('desserts', 'Dessert')], default='mains', max_length=30),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='spice',
            field=models.CharField(choices=[('mild', 'Mild'), ('spiceless', 'Spiceless'), ('atomic', 'Atomic'), ('hot', 'Hot')], default='spiceless', max_length=15),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('CKG', 'Cooking'), ('COM', 'Completed'), ('RTC', 'Ready to collect'), ('UPD', 'Not paid for'), ('REC', 'Received')], max_length=3),
        ),
    ]
